artifact_location: /Users/dominikpichler/Documents/Git/LST-ME_KNOW/src/your_mlflow_tracking_uri/0
creation_time: 1720625113283
experiment_id: '0'
last_update_time: 1720625113283
lifecycle_stage: active
name: Default
