artifact_uri: /Users/dominikpichler/Documents/Git/LST-ME_KNOW/src/your_mlflow_tracking_uri/0/69f12f7c6f1743b0bc8930ed267dc976/artifacts
end_time: 1720625404527
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 69f12f7c6f1743b0bc8930ed267dc976
run_name: painted-fox-733
run_uuid: 69f12f7c6f1743b0bc8930ed267dc976
source_name: ''
source_type: 4
source_version: ''
start_time: 1720625394513
status: 3
tags: []
user_id: dominikpichler
