channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.0
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - dill==0.3.8
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - pyyaml==6.0.1
  - torch==2.3.1
  - tqdm==4.66.4
name: mlflow-env
