artifact_uri: /Users/dominikpichler/Documents/Git/LST-ME_KNOW/src/your_mlflow_tracking_uri/0/20440a8251664eebbb901cb8c6858dc0/artifacts
end_time: 1720625332004
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 20440a8251664eebbb901cb8c6858dc0
run_name: persistent-lark-611
run_uuid: 20440a8251664eebbb901cb8c6858dc0
source_name: ''
source_type: 4
source_version: ''
start_time: 1720625311534
status: 3
tags: []
user_id: dominikpichler
